# These are supported funding model platforms

github: [AndroiableDroid, firewolfxda, manjotsidhu, rezaadi0105]
patreon: # TODO
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: #TODO https://pbrp.ml/donate
